name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test-install-ubuntu-20-04:
    name: "Test installation on Ubuntu 20.04"
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pyDISORT
        run: |
          python -m pip install .
      - name: Test the installation
        run: |
          python
          import disort
          disort.disort.__doc__
  #test-install-ubuntu-18-04:
  #  name: "Test installation on Ubuntu 18.04"
  #  runs-on: ubuntu-18.04

  #test-fortran-big-sur-11:
  #  name: "Test installation on macOS Big Sur 11"
  #  runs-on: macos-10.15

  #test-fortran-catalina-10-15:
  #  name: "Test installation on macOS Catalina 10.15"
  #  runs-on: macos-10.15
